package cms
/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
  def filters = {
    cmsAdmin(uri: "/wcm/admin/**") {
      before = {
        accessControl()
      }
    }
    profiles(uri: "/profile/**") {
      before = {
        accessControl()
      }
    }
    profiles(uri: "/localLogon/**") {
      before = {
        accessControl()
      }
    }
    stockAdmin(uri: "/stock/**") {
      before = {
        accessControl()
      }
    }
  }
}
